### PR TITLE
Implement timer feature and load minutes and seconds into winner card

### PR DESCRIPTION
**Pull request by MandyAlford**
### Type of change made:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Detailed Description
Capture total minutes and seconds it takes to correctly guess the number, starting from when the range is submitted (update button) until the correct number is submitted. Minutes and seconds are interpolated into the winner card.

### Why is this change required? What problem does it solve?
This creates a better user experience and adds an additional layer of competitiveness to the game.

### Were there any challenges that arose while implementing this feature? If so, how were the addressed?
Just overthinking how to best capture the time elapsed during the game.

### Files modified:
- [ ] index.html
- [ ] styles.css
- [X] main.js
- [ ] Other files:

### CODE REVIEW

**Comment by tanishaldavey** [comment]
The syntax for the timer function is easy to read and follow. Just wondering why there were parameters in the dispalyWinnerCard function? What are those being used for?

**Comment by MandyAlford** [comment]
Passing through the minutes and seconds into the displayWinnerCard function allowed me to grab hold of those numbers and use them outside of the function that created them without declaring another global variable. (And it was something I wanted to try and see if it worked!)

**Comment by tanishaldavey** [comment]
Okay, understood! I agree with that being a great way to grab hold of those arguments without declaring a global variable!

**Comment by MandyAlford** [comment]
I'd love to try and reduce our global variables in the refactoring phase if time allows!

**Pull request merged**
